#
# Rocky Linux 9 + PostgreSQL 18 image for testing pg_enhanced_query_logging.
#
# Build:
#   docker build -f test/Dockerfile.pg18-rhel -t peql-pg18-rhel .
#
# Run:
#   docker run -d --name peql-pg18-rhel-test \
#       -e POSTGRES_PASSWORD=peqltest -p 15433:5432 peql-pg18-rhel
#
FROM rockylinux:9

ARG PG_MAJOR=18

RUN dnf -y install \
        https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm && \
    dnf -y install 'dnf-command(config-manager)' && \
    dnf config-manager --set-enabled crb && \
    dnf -y --allowerasing install \
        postgresql${PG_MAJOR}-server \
        postgresql${PG_MAJOR}-devel \
        postgresql${PG_MAJOR}-llvmjit \
        gcc \
        clang \
        llvm-devel \
        make \
        redhat-rpm-config \
        openssl-devel \
        krb5-devel \
        libxml2-devel \
        lz4-devel \
        curl \
        perl-core && \
    dnf clean all

ENV PATH="/usr/pgsql-${PG_MAJOR}/bin:${PATH}" \
    PGDATA="/var/lib/pgsql/${PG_MAJOR}/data"

COPY . /tmp/pg_enhanced_query_logging

RUN cd /tmp/pg_enhanced_query_logging && \
    make clean USE_PGXS=1 2>/dev/null || true && \
    make USE_PGXS=1 -j"$(nproc)" && \
    make install USE_PGXS=1 && \
    rm -rf /tmp/pg_enhanced_query_logging

RUN curl -sSL -o /usr/local/bin/pt-query-digest https://percona.com/get/pt-query-digest && \
    chmod +x /usr/local/bin/pt-query-digest && \
    chown root:root /usr/local/bin/pt-query-digest

RUN su - postgres -c " \
    /usr/pgsql-${PG_MAJOR}/bin/initdb --pgdata=${PGDATA} && \
    echo \"shared_preload_libraries = 'pg_enhanced_query_logging'\" >> ${PGDATA}/postgresql.conf && \
    echo \"peql.log_min_duration = 0\"   >> ${PGDATA}/postgresql.conf && \
    echo \"peql.log_verbosity = 'full'\" >> ${PGDATA}/postgresql.conf && \
    echo \"track_io_timing = on\"        >> ${PGDATA}/postgresql.conf && \
    echo \"listen_addresses = '*'\"      >> ${PGDATA}/postgresql.conf && \
    \
    echo \"shared_buffers = '12GB'\"              >> ${PGDATA}/postgresql.conf && \
    echo \"effective_cache_size = '36GB'\"         >> ${PGDATA}/postgresql.conf && \
    echo \"work_mem = '128MB'\"                   >> ${PGDATA}/postgresql.conf && \
    echo \"maintenance_work_mem = '2GB'\"          >> ${PGDATA}/postgresql.conf && \
    echo \"wal_buffers = '64MB'\"                 >> ${PGDATA}/postgresql.conf && \
    echo \"checkpoint_timeout = '30min'\"          >> ${PGDATA}/postgresql.conf && \
    echo \"checkpoint_completion_target = 0.9\"   >> ${PGDATA}/postgresql.conf && \
    echo \"max_wal_size = '10GB'\"                >> ${PGDATA}/postgresql.conf && \
    echo \"min_wal_size = '1GB'\"                 >> ${PGDATA}/postgresql.conf && \
    echo \"random_page_cost = 1.1\"               >> ${PGDATA}/postgresql.conf && \
    echo \"effective_io_concurrency = 200\"        >> ${PGDATA}/postgresql.conf && \
    echo \"max_parallel_workers_per_gather = 4\"  >> ${PGDATA}/postgresql.conf && \
    echo \"max_parallel_workers = 8\"             >> ${PGDATA}/postgresql.conf && \
    echo \"max_worker_processes = 16\"            >> ${PGDATA}/postgresql.conf && \
    echo \"max_connections = 200\"                >> ${PGDATA}/postgresql.conf && \
    echo \"bgwriter_lru_maxpages = 400\"          >> ${PGDATA}/postgresql.conf && \
    echo \"bgwriter_lru_multiplier = 4.0\"        >> ${PGDATA}/postgresql.conf && \
    \
    echo 'host all all 0.0.0.0/0 md5'   >> ${PGDATA}/pg_hba.conf && \
    echo 'host all all ::/0      md5'   >> ${PGDATA}/pg_hba.conf \
"

EXPOSE 5432

USER postgres
CMD ["/usr/pgsql-18/bin/postgres"]
